<a href="https://colab.research.google.com/github/PabloJRW/TensorFlow_Developer_Certificate/blob/main/Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
#Finding the positional minimum and maximum of a tensor 
a = tf.Variable([[23,35,49],[6,42, 36],[38,86,33]])

In [ ]:
# Change from float32 to float16
a = tf.cast(a, dtype=tf.float16)
a

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[23., 35., 49.],
       [ 6., 42., 36.],
       [38., 86., 33.]], dtype=float16)>

In [ ]:
# Find the maximum
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=float16, numpy=86.0>

In [ ]:
# Find the mean
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=float16, numpy=38.66>

In [ ]:
# Find the sum
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=float16, numpy=348.0>

In [ ]:
# Find the variance, we need acccess to tensorflow_probability
import tensorflow_probability as tfp
tfp.stats.variance(a)

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([170.9 , 509.2 ,  48.25], dtype=float16)>

In [ ]:
# Find the standard deviation
tf.math.reduce_std(a)

<tf.Tensor: shape=(), dtype=float16, numpy=20.34>

Find the positional maximum and minimum

In [ ]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
f = tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the positional maximum
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Index on our largest value position
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Find the max value of f
tf.reduce_max(f) 

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Check for equality
f[tf.argmax(f)] == tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find the positionalminimum
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Find the positional minimum
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removimg all single dimensions)

In [ ]:
# Create a tensor 
tf.random.set_seed(42)
g = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
g.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
g_squeezed = tf.squeeze(g)
g_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
g_squeezed.shape

TensorShape([50])

### One-hot encoding

In [ ]:
# Create a list of indices
indices = [0, 1, 2, 3, 2, 3, 1]

# One hot encode our list of indices
tf.one_hot(indices, depth=4)

<tf.Tensor: shape=(7, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
texto = "el carro rojo es más veloz que el carro azul"
tf.one_hot(indices, depth=4, on_value="SI", off_value="NO", )

<tf.Tensor: shape=(7, 4), dtype=string, numpy=
array([[b'SI', b'NO', b'NO', b'NO'],
       [b'NO', b'SI', b'NO', b'NO'],
       [b'NO', b'NO', b'SI', b'NO'],
       [b'NO', b'NO', b'NO', b'SI'],
       [b'NO', b'NO', b'SI', b'NO'],
       [b'NO', b'NO', b'NO', b'SI'],
       [b'NO', b'SI', b'NO', b'NO']], dtype=object)>

### Squaring, Log, Square Root

In [ ]:
# Create a ne tensor
h = tf.range(-3, 10)
h

<tf.Tensor: shape=(13,), dtype=int32, numpy=array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9], dtype=int32)>

In [ ]:
# Square tensor
tf.square(h)

<tf.Tensor: shape=(13,), dtype=int32, numpy=array([ 9,  4,  1,  0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find square root
tf.sqrt(tf.cast(h, dtype=tf.float32))

<tf.Tensor: shape=(13,), dtype=float32, numpy=
array([      nan,       nan,       nan, 0.       , 1.       , 1.4142135,
       1.7320508, 2.       , 2.236068 , 2.4494898, 2.6457512, 2.828427 ,
       3.       ], dtype=float32)>

In [ ]:
# Find the log 
tf.math.log(tf.cast(h, dtype=tf.float32))

<tf.Tensor: shape=(13,), dtype=float32, numpy=
array([      nan,       nan,       nan,      -inf, 0.       , 0.6931472,
       1.0986123, 1.3862944, 1.609438 , 1.7917595, 1.9459101, 2.0794415,
       2.1972246], dtype=float32)>